import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans_KR({
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Person Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSans.className} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
